# Generated by Django 2.2.5 on 2022-04-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='top_names',
            new_name='top_name',
        ),
    ]
